# Generated by Django 5.1.7 on 2025-05-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('payment_type', models.CharField(max_length=50)),
                ('days_for_shipping_real', models.IntegerField()),
                ('days_for_shipment_scheduled', models.IntegerField()),
                ('delivery_status', models.CharField(max_length=50)),
                ('late_delivery', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=100)),
                ('store_city', models.CharField(max_length=100)),
                ('store_country', models.CharField(max_length=100)),
                ('category_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_segment', models.CharField(max_length=50)),
                ('customer_zipcode', models.CharField(max_length=20)),
                ('store_state', models.CharField(max_length=100)),
                ('store_street', models.CharField(max_length=200)),
                ('department_id', models.IntegerField()),
                ('department_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('market', models.CharField(max_length=50)),
                ('order_city', models.CharField(max_length=100)),
                ('order_country', models.CharField(max_length=100)),
                ('order_customer_id', models.IntegerField()),
                ('order_datetime', models.DateTimeField()),
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_item_cardprod_id', models.IntegerField()),
                ('order_item_discount', models.FloatField()),
                ('item_discount_rate', models.FloatField()),
                ('order_item_id', models.IntegerField()),
                ('item_product_price', models.FloatField()),
                ('item_profit_ratio', models.FloatField()),
                ('item_quantity', models.IntegerField()),
                ('item_subtotal', models.FloatField()),
                ('item_total', models.FloatField()),
                ('profit_per_item', models.FloatField()),
                ('order_region', models.CharField(max_length=50)),
                ('order_state', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=50)),
                ('product_id', models.IntegerField()),
                ('product_category_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('shipping_datetime', models.DateTimeField()),
                ('shipping_mode', models.CharField(max_length=50)),
            ],
        ),
    ]
